global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'backend-service:8080' ]
        labels:
          application: 'Backend Service'