spring:
  config:
    activate:
      on-profile: test
  devtools:
    add-properties: true
  jpa:
    # Provide database platform that is being used
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # New database is created when app starts and destroyed when app stops
      ddl-auto: none
    # Show sql when spring data jpa performs query
    show-sql: false
    properties:
      hibernate:
        # Format queries
        format_sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: backend-service
    server: ${BACKEND_ENDPOINT:http://localhost:${server.port}}
    title: Backend service
    version: 1.0.0