server:
  port: 8080

spring:
  application:
    name: backend-service
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: '*'
#  endpoint:
#    health:
#      probes:
#        enabled: true
#  health:
#    livenessState:
#      enabled: true
#    readinessState:
#      enabled: true
#  prometheus:
#    metrics:
#      export:
#        step: 5s
#        enabled: true

logging:
  level:
    root: INFO
    web: INFO
    org.springframework: OFF
#  file:
#    name: ${spring.application.name}.log
#  logback:
#    rollingpolicy:
#      file-name-pattern: backend-service-%d{yyyy-MM-dd}.%i.log
#      max-file-size: 1MB
#      total-size-cap: 10MB
#      max-history: 30
#      clean-history-on-start: true