spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/testdb?allowPublicKeyRetrieval=true&useSSL=false}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate:
      ddl-auto: none
  sendgrid:
    api-key: ${SENDGRID_API_KEY:DUMMY-SENDGRID-API-KEY}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

jwt:
  expiryMinutes: 60
  expiryDay: 14
  accessKey: c2VjcmV0QGtleS5hcGlfaGFzX2JlZW5fZGVzaWduZWRfYnlfVGF5TFE=
  refreshKey: 9k1jJAWAKQCnCEz1pwcPNegbHoLugf9hgEnn6sz5pFc=